### ISSUE TITLE
XCode13, React Native passbase library cannot upload to Appstore

### ISSUE THREAD

**Issue by chainpioneer1** [passbase/react-native-demo-app#7]
Hello admin.
I'm trying to use @passbase/react-native-passbase 2.12.0 library.
And on android, it has no problem.
But on iOS build, it uses microblink 5.15.2 library as dependency, but it is rejected by appstore.

Basically, it shows this  error when  build.
The bundle at '.../Frameworks/Microblink.framework' contains disallowed file 'Frameworks'. With error code STATE_ERROR.VALIDATION_ERROR.90206 for id 8cb0ca18-f4be-405d-91e7-6efb0dee6515

It can bypass using this method, 
https://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr

But finally, when uploading to testflight, it gives "Invalid Binary" error.

Anyone have solution for this problem? If so, please kindly provide answer.
Thank you.

**Comment by skorostetskyi** [comment]
Hi @AstonishGong,
Please update Passbase React Native SDK to the latest version. It contains the fix.
